version: "3.8"

services:
  n8n:
    build: .
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=""
      - N8N_BASIC_AUTH_PASSWORD=""
      - WEBHOOK_URL=https://n8n-lighthouse.fly.dev/
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - TZ=Europe/Paris
    volumes:
      - .n8n:/home/node/.n8n